### ISSUE TITLE
No temperature on sensor

### ISSUE THREAD

**Issue by naamah75** [TheRealWaldo/thermal#171] opened 2022-10-30 07:30 UTC
I am using the latest version compiled with Arduino IDE (PIO Home gives me compatibility problems with 64 bit libraries), with the latest version of the component for Home Assistant and also the latest version of Home Assistant.
I'm able to get the camera image and the presence occupancy, but not the temperature.

This is my components status:

```
GitHub TheRealWaldo/thermal 072bb1f on 27 Aug 2021

Thermal Vision 3.1.2 

Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
```

This is my config on HA:

```
- platform: thermal_vision
  unique_id: thermal_vision_camera
  host: http://192.168.4.81
  auto_range: yes
  min_diff: 8
  rotate: 180
  width: 320
  height: 320
  mirror: true
  overlay: true

- platform: thermal_vision
  unique_id: thermal_vision_binary_sensor
  host: http://192.168.4.81

  - platform: thermal_vision
    unique_id: thermal_vision_sensor
    host: http://192.168.4.81
```

![image](https://user-images.githubusercontent.com/34965103/198867159-3545d610-6c97-4e1a-b8e1-1c8ea1728300.png)

**Comment by TheRealWaldo** [comment] 2022-10-31 15:18
This is likely a duplicate of #169

**Closed** 2022-11-21 17:10 UTC
